// Generated by typed-directory on 02/02/2018 14:41:31
import BaseClass from "./BaseClass";

import _Something from "./content/Something";
import _SomethingElse from "./content/SomethingElse";

const Something:{new(): BaseClass} = _Something;
const SomethingElse:{new(): BaseClass} = _SomethingElse;

export default {
	"Something": Something,
	"SomethingElse": SomethingElse
};