// Generated by typed-directory on 02/02/2018 14:41:31
import Animal from "./Animal";

import _domestic_cat from "./content/domestic/cat";
import _domestic_dog from "./content/domestic/dog";
import _zoo_lion from "./content/zoo/lion";

const domestic_cat:Animal = _domestic_cat;
const domestic_dog:Animal = _domestic_dog;
const zoo_lion:Animal = _zoo_lion;

export default {
	"domestic": {
		"cat": domestic_cat,
		"dog": domestic_dog
	},
	"zoo": {
		"lion": zoo_lion
	}
};