// Generated by typed-directory on 01/28/2018 16:48:22
import BaseClass from "./BaseClass";

import _Something from "./content/Something";
import _SomethingElse from "./content/SomethingElse";

const Something:{new(): BaseClass} = _Something;
const SomethingElse:{new(): BaseClass} = _SomethingElse;

export default {
	"Something": Something,
	"SomethingElse": SomethingElse
};